spring.application.name=msvc-items
server.port=8002

spring.datasource.url=jdbc:postgresql://localhost:5432/micro_servicios
spring.datasource.username=postgres
spring.datasource.password=usuario
spring.datasource.driver-class-name=org.postgresql.Driver
spring.cloud.discovery.client.simple.instances.msvc-products[0].uri=http://localhost:8001
spring.cloud.discovery.client.simple.instances.msvc-products[1].uri=http://localhost:9001


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true